services:
  app:
    image: crpi-cwyvl6vckkv4k4p7.cn-hangzhou.personal.cr.aliyuncs.com/nuguri_ddd/ddd:latest
    ports:
      - "8000:8000"
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
